---
- name: Create Storage Group
  hosts: create_storagegroup
  connection: local
  gather_facts: false

  # TODO: make pre-task to a separat role for EE
  pre_tasks:  
    - name: Check whether a package called PyU4U is installed
      ansible.builtin.command: 'pip3 show PyU4V'
      ignore_errors: true
      changed_when: result.rc != 0 # <- Uses the return code to define when the task has changed.
      register: result

    - name: Print out package installation status
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Run python3 -m site
      ansible.builtin.command: python3 -m site
      register: site_output

    - name: Display site paths
      debug:
        msg: "{{ site_output.stdout_lines }}"

  roles:
    - create_storagegroup
