---
- name: Create Storage Group
  hosts: create_storagegroup
  connection: local
  gather_facts: false
  # become: true
  # become_method: sudo

  pre_tasks:  
    - name: Check whether a package called PyU4U is installed
      ansible.builtin.command: 'pip3 show PyU4V'
      ignore_errors: true
      changed_when: result.rc != 0 # <- Uses the return code to define when the task has changed.
      register: result

    - name: Print out package installation status
      ansible.builtin.debug:
        msg: "{{ result }}"

  tasks:
    - name: Create Storage Group
      collections:
        - dellemc.powermax
      dellemc.powermax.storagegroup:
        unispherehost: "{{ unispherehost }}"
        universion: "{{ universion }}"
        verifycert: "{{ verifycert }}"
        user: "{{ user }}"
        password: "{{ password }}"
        serial_no: "{{ serial_no }}"
        sg_name: "{{ sg_name }}"
        state: "present"
      register: new_sg

    - name: Print out new created storage group
      ansible.builtin.debug:
        msg: "{{ new_sg }}"  

  # roles:
  #   - create_storagegroup
