---
# tasks file for prerequisites
- name: Install PyU4V
  ansible.builtin.pip:
    name: "{{ PyU4V_version }}"
    # name: PyU4V==10.1.0.0
    # virtualenv: ~/venv
    # virtualenv_site_packages: true
    # executable: pip3
 # become: true
