---
# tasks file for create_storagegroup
# demo only - no additional logic in this role

# - name: Install prerequisites PyU4V
#   ansible.builtin.pip:
#     # name: "{{ PyU4V_version }}"
#     name: PyU4V==10.1.0.0
#     extra_args: --user

- name: Create Storage Group
  collections:
    - dellemc.powermax
  dellemc.powermax.storagegroup:
    unispherehost: "{{ unispherehost }}"
    universion: "{{ universion }}"
    verifycert: "{{ verifycert }}"
    user: "{{ user }}"
    password: "{{ password }}"
    serial_no: "{{ serial_no }}"
    sg_name: "{{ sg_name }}"
    state: "present"
  register: new_sg

- name: Print out new created storage group
  ansible.builtin.debug:
    msg: "{{ new_sg }}"
