---
# tasks file for create_storagegroup
# demo only - no additional logic in this role

# - name: Install prerequisites PyU4V
#   ansible.builtin.pip:
#     # name: "{{ PyU4V_version }}"
#     name: PyU4V==10.1.0.0
#     extra_args: --user


# - name: Check whether a package called PyU4U is installed
#   ansible.builtin.command: 'pip3 show PyU4V'
#   ignore_errors: true
#   register: result
#   changed_when: result.rc != 0 # <- Uses the return code to define when the task has changed.

# - name: Print out package installation status
#   ansible.builtin.debug:
#     msg: "{{ result }}"

- name: Create Storage Group
  collections:
    - dellemc.powermax
  dellemc.powermax.storagegroup:
    unispherehost: "{{ unispherehost }}"
    universion: "{{ universion }}"
    verifycert: "{{ verifycert }}"
    user: "{{ user }}"
    password: "{{ password }}"
    serial_no: "{{ serial_no }}"
    sg_name: "{{ sg_name }}"
    state: "present"
  register: new_sg

- name: Print out new created storage group
  ansible.builtin.debug:
    msg: "{{ new_sg }}"
